"""Main pipeline orchestrator — drives the Astra development lifecycle via Agent SDK."""

from __future__ import annotations

import asyncio
import re

from rich.console import Console

from orchestrator.checks.base import CheckStatus
from orchestrator.checks.design_checks import run_design_checks
from orchestrator.checks.phase_checks import run_phase_checks
from orchestrator.checks.plan_checks import run_plan_checks
from orchestrator.checks.spec_checks import run_spec_checks
from orchestrator.checks.tech_checks import run_tech_checks
from orchestrator.config import AstraConfig
from orchestrator.stages.architect import ArchitectStage
from orchestrator.stages.base import StageResult
from orchestrator.stages.design import DesignStage
from orchestrator.stages.implement import ImplementStage
from orchestrator.stages.plan import PlanStage
from orchestrator.stages.review import ReviewStage
from orchestrator.stages.spec import SpecStage
from orchestrator.state import PipelineState

console = Console()

MAX_RETRIES = 2


async def _run_codebase_scan(config: AstraConfig, state: PipelineState) -> None:
    """Step 0d: Scan codebase and write .astra-cache/context.md."""
    from claude_agent_sdk import ClaudeAgentOptions, ResultMessage, query

    console.print("  [bold]Scan[/] — caching codebase context...")

    prompt = (
        "Scan this project and produce a codebase context summary. Include:\n"
        "- Tech Stack (framework, language, database, styling, testing)\n"
        "- Project Structure (component paths, API routes, models, tests, config)\n"
        "- Frontend Patterns (component library, design tokens, CSS approach, layout)\n"
        "- Backend Patterns (API style, auth, ORM, error handling)\n"
        "- Conventions (file naming, test location, import aliases)\n\n"
        "Read config files first (package.json, tsconfig, pyproject.toml, etc.), "
        "then targeted Glob for key directories. Read 1-2 representative files per category.\n\n"
        "Return ONLY the markdown summary — no explanations."
    )

    opts = ClaudeAgentOptions(
        allowed_tools=["Read", "Grep", "Glob", "Bash"],
        permission_mode="default",
        cwd=str(config.project_dir),
    )

    output = ""
    try:
        async for message in query(prompt=prompt, options=opts):
            if isinstance(message, ResultMessage) and hasattr(message, "result"):
                output = message.result or ""
    except Exception as e:
        console.print(f"  [yellow]Scan warning: {e}[/]")
        output = f"# Codebase Context (scan failed)\n\nError: {e}\n"

    if output:
        config.context_cache_path.write_text(
            f"# Codebase Context (auto-generated by astra-forge)\n\n{output}",
            encoding="utf-8",
        )
    state.mark_complete("scan")
    state.save(config.state_path)
    console.print("  [green]✓[/] Context cached")


def _detect_mode(spec_text: str, force_lite: bool) -> str:
    """Detect full vs lite mode from spec content."""
    if force_lite:
        return "lite"

    req_pattern = re.compile(r"^###\s+R\d+:", re.MULTILINE)
    req_count = len(req_pattern.findall(spec_text))

    # Check if mixed frontend+backend
    has_frontend = bool(re.search(r"UI|component|page|frontend|button|form|display", spec_text, re.IGNORECASE))
    has_backend = bool(re.search(r"API|endpoint|database|model|migration|backend", spec_text, re.IGNORECASE))
    is_mixed = has_frontend and has_backend

    if req_count <= 3 and not is_mixed:
        return "lite"
    return "full"


async def _run_stage_with_retry(
    stage,
    state: PipelineState,
    config: AstraConfig,
    stage_name: str,
) -> StageResult:
    """Run a stage with two-strike retry logic."""
    state.advance_to(stage_name)
    state.save(config.state_path)

    result = await stage.run(state, config)

    if not result.success:
        retry = state.increment_retry(stage_name)
        if retry < MAX_RETRIES:
            console.print(f"  [yellow]Retrying {stage_name} (attempt {retry + 1}/{MAX_RETRIES})...[/]")
            result = await stage.run(state, config)

        if not result.success:
            state.mark_failed(stage_name, result.error or "Unknown error")
            state.save(config.state_path)
            console.print(f"  [red]✗ {stage_name} failed after {MAX_RETRIES} attempts: {result.error}[/]")
            return result

    state.mark_complete(stage_name, result.artifact_path, result.session_id)
    state.save(config.state_path)
    return result


def _run_gate(gate_result, state, config, stage_name) -> bool:
    """Run gate checks, print summary, return True if passed."""
    gate_result.print_summary()
    state.record_gate(stage_name, gate_result.to_dict())
    state.save(config.state_path)

    if not gate_result.passed:
        console.print(f"  [red]✗ {stage_name} gate failed[/]")
        return False
    return True


async def run_pipeline(
    config: AstraConfig,
    feature: str,
    resume_id: str | None = None,
) -> None:
    """Execute the full Astra forge pipeline."""
    console.print(f"\n[bold cyan]Astra Forge v2[/] — {feature}\n")

    # Load or create state
    state = PipelineState.load_or_create(
        path=config.state_path,
        feature=feature,
        mode="lite" if config.lite else "full",
    )

    console.print(f"  Pipeline: {state.pipeline_id}")
    if config.dry_run:
        console.print("  [yellow]Dry run mode[/]")
    console.print()

    # ── Step 0: Codebase scan ──────────────────────────────────
    if not state.stage_complete("scan"):
        await _run_codebase_scan(config, state)

    # ── Step 1: PM → SPEC.md ──────────────────────────────────
    if not state.stage_complete("spec"):
        result = await _run_stage_with_retry(SpecStage(), state, config, "spec")
        if not result.success:
            return

        # Detect mode from spec
        spec_path = config.project_dir / "SPEC.md"
        if spec_path.is_file():
            mode = _detect_mode(spec_path.read_text(), config.lite)
            state.init_stages(mode)
            state.mark_complete("spec", "SPEC.md", result.session_id)
            state.save(config.state_path)
            console.print(f"  Mode: [bold]{mode}[/]")

        # Spec gate
        gate = run_spec_checks(feature, config.project_dir / "SPEC.md")
        if not _run_gate(gate, state, config, "spec"):
            return

        if config.interactive:
            console.print("\n  [yellow]Interactive: Review SPEC.md. Press Enter to continue or Ctrl+C to stop.[/]")
            input()

    # ── Step 2: Design + Plan ──────────────────────────────────
    if state.mode == "full":
        # Parallel: Designer + Planner
        tasks = []
        if not state.stage_complete("design"):
            tasks.append(("design", _run_stage_with_retry(DesignStage(), state, config, "design")))
        if not state.stage_complete("plan"):
            tasks.append(("plan", _run_stage_with_retry(PlanStage(), state, config, "plan")))

        if tasks:
            console.print("  [dim]Running Designer + Planner in parallel...[/]")
            results = await asyncio.gather(*[t[1] for t in tasks], return_exceptions=True)
            for (name, _), result in zip(tasks, results):
                if isinstance(result, Exception):
                    state.mark_failed(name, str(result))
                    state.save(config.state_path)
                    console.print(f"  [red]✗ {name} failed: {result}[/]")
                    return
                if not result.success:
                    return

        # Design gate
        if state.mode == "full":
            dgate = run_design_checks(
                config.project_dir / "SPEC.md",
                config.project_dir / "DESIGN.md",
            )
            _run_gate(dgate, state, config, "design")

        # Plan gate
        pgate = run_plan_checks(
            config.project_dir / "SPEC.md",
            config.project_dir / "PLAN.md",
        )
        if not _run_gate(pgate, state, config, "plan"):
            return

        if config.interactive:
            console.print("\n  [yellow]Interactive: Review DESIGN.md + PLAN.md. Press Enter to continue.[/]")
            input()
    else:
        # Lite mode: plan only
        if not state.stage_complete("plan"):
            result = await _run_stage_with_retry(PlanStage(), state, config, "plan")
            if not result.success:
                return

            pgate = run_plan_checks(
                config.project_dir / "SPEC.md",
                config.project_dir / "PLAN.md",
            )
            if not _run_gate(pgate, state, config, "plan"):
                return

    # ── Step 3: Architect → TECHNICAL.md ───────────────────────
    if state.mode == "full" and not state.stage_complete("architect"):
        result = await _run_stage_with_retry(ArchitectStage(), state, config, "architect")
        if not result.success:
            return

        tgate = run_tech_checks(
            config.project_dir / "SPEC.md",
            config.project_dir / "TECHNICAL.md",
            config.project_dir / "PRODUCT.md",
        )
        if not _run_gate(tgate, state, config, "architect"):
            return

        if config.interactive:
            console.print("\n  [yellow]Interactive: Review TECHNICAL.md. Press Enter to continue.[/]")
            input()

    # ── Step 4: Implementation ─────────────────────────────────
    if not state.stage_complete("implement"):
        result = await _run_stage_with_retry(ImplementStage(), state, config, "implement")
        if not result.success:
            return

        # Phase gate
        phgate = await run_phase_checks(config.project_dir, config.project_dir / "SPEC.md")
        _run_gate(phgate, state, config, "implement")

    # ── Step 5: Review ─────────────────────────────────────────
    if not state.stage_complete("review"):
        result = await _run_stage_with_retry(ReviewStage(), state, config, "review")
        if not result.success:
            return
        state.mark_complete("review", session_id=result.session_id)
        state.save(config.state_path)
        console.print(f"  [green]✓[/] Review complete")

    # ── Step 6: Wrap-up ────────────────────────────────────────
    if not state.stage_complete("wrapup"):
        state.mark_complete("wrapup")
        state.completed_at = __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat()
        state.save(config.state_path)

        # Clean up cache (except state file for resume reference)
        if config.context_cache_path.is_file():
            config.context_cache_path.unlink()

        console.print()
        console.print("[bold green]Pipeline complete![/]")
        console.print(f"  Feature: {feature}")
        console.print(f"  Mode: {state.mode}")
        console.print(f"  Artifacts: SPEC.md", end="")
        if state.mode == "full":
            console.print(", DESIGN.md, PLAN.md, TECHNICAL.md")
        else:
            console.print(", PLAN.md")
        console.print()
        console.print("  Next: `astra-forge schedule` or `/astra:ship` to commit + PR")
